import = ["~/.config/alacritty/mate-terminal.toml"]
live_config_reload = true

[font]
normal = { family = "SauceCodePro Nerd Font Propo", style = "Medium" }
# size = 11.25
# size = 17.25
# 8 clicks is -6 from the value wtf?!?!?
size = 12.75
builtin_box_drawing = true
